biddr_app/config/routes.rb
Rails.application.routes.draw do
  resources :auctions do
    resources :bids, only: [:create, :destroy]
  end


  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
        resources :auctions, only: [:index, :show, :create, :update, :destroy] do
          resources :bids, only: [:create, :destroy]
        end
        resources :tokens, only:[:create]
    end
end


  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

biddr_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAnswers</title>
    <%= csrf_meta_tags %>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyBq3hprXGllrVUctOkE219bg0e0e-u1118"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <!-- <a href='/'>Home</a>
    |
    <a href='/hello'>About Us</a> -->
    <%= link_to('Home', root_path) %>
    <%# the above👆 generates: <a href='/'>Home</a> %>
    |
    <%= link_to 'Auctions', auctions_path %>
    |
    <%= link_to 'New Auction', new_auction_path %>
    |
    <% if user_signed_in? %>
      <span>Hello, <%= current_user.first_name %> <%= current_user.last_name %></span>
      |
      <%= link_to 'Sign Out', session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign Up', new_user_path %>
      |
      <%= link_to 'Sign In', new_session_path %>
    <% end %>
    <hr>

    <div class="container-fluid">
      <% if flash[:notice].present? %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:alert].present? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>