biddr_app/config/routes.rb
Rails.application.routes.draw do
  resources :auctions do
    resources :bids, only: [:create, :destroy]
  end


  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
        resources :auctions, only: [:index, :show, :create, :update, :destroy] do
          resources :bids, only: [:create, :destroy]
        end
        resources :tokens, only:[:create]
    end
end


  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

biddr_app/app/models/auction.rb
class Auction < ApplicationRecord
  has_many :bids, dependent: :destroy
  belongs_to :user
end

biddr_app/app/controllers/api/v1/auctions_controller.rb
class Api::V1::AuctionsController < Api::BaseController
  before_action :authenticate_api_user

  def index
    @auctions = Auction.order(created_at: :desc).limit(20)
    # render json: @auctions

    # this will render views/api/v1/index.json.jbuilder
  end

  def show
    auction = Auction.find params[:id]
    # Because we installed ActiveModel Serializer then the default behaviour is
    # to use the serializer instead of the default `to_json` method that comes
    # with ActiveRecrod
    render json: auction
  end

  def create
    auction = Auction.new auction_params
    auction.user = current_user
    if auction.save
      render json: auction
    else
      render json: { errors: auction.errors.full_messages }
    end
  end

  def update
    auction = Auction.find params[:id]
    if auction.update auction_params
      render json: { success: true }
    else
      render json: { errors: auction.errors.full_messages }
    end
  end

  def destroy
    auction = Auction.find_by_id params[:id]
    if auction
      auction.destroy
      render json: { success: true }
    else
      render json: { errors: ['auction doesn\'t exist'] }
    end
  end

  private

  def auction_params
    params.require(:auction).permit(:title, :description, :endson, :price)
  end
end

biddr_app/app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user!, except: [:index, :show, :new, :create]

  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.all
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
    @auction = Auction.find params[:id]
    @bid = Bid.new
    @bids = @auction.bids.order(created_at: :desc)

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @auction }
    end
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(auction_params)
    @auction.user = current_user


    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url, notice: 'Auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_params
      params.require(:auction).permit(:title, :description, :endson, :price)
    end
end

biddr_app/app/helpers/auctions_helper.rb
module AuctionsHelper
end

biddr_app/app/views/auctions/_form.html.erb
<%= form_with(model: auction, local: true) do |form| %>
  <% if auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% auction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :auction_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :auction_description %>
  </div>

  <div class="field">
    <%= form.label :endson %>
    <%= form.date_select :endson, id: :auction_endson %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :auction_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

biddr_app/app/views/auctions/edit.html.erb
<h1>Editing Auction</h1>

<%= render 'form', auction: @auction %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

biddr_app/app/views/auctions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Auctions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Endson</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auctions.each do |auction| %>
      <tr>
        <td><%= auction.title %></td>
        <td><%= auction.description %></td>
        <td><%= auction.endson %></td>
        <td><%= auction.price %></td>
        <td><%= link_to 'Show', auction %></td>
        <td><%= link_to 'Edit', edit_auction_path(auction) %></td>
        <td><%= link_to 'Destroy', auction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auction', new_auction_path %>

biddr_app/app/views/auctions/new.html.erb
<h1>New Auction</h1>

<%= render 'form', auction: @auction %>

<%= link_to 'Back', auctions_path %>

biddr_app/app/views/auctions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @auction.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @auction.description %>
</p>

<p>
  <strong>Endson:</strong>
  <%= @auction.endson %>
</p>

<p>
  <strong>Price:</strong>
  <%= @auction.price %>
</p>

<%= link_to 'Edit', edit_auction_path(@auction) %> |
<%= link_to 'Back', auctions_path %>

<%= form_for [@auction, @bid] do |f| %>
  <%= f.text_area :bid %>
  <%= f.submit %>
<% end %>

  <% @bids.each do |bid| %>
      <p><%= bid.bid %></p>
      <p>By <%= bid.user&.full_name %></p>
      <p><strong>Created At:</strong> <%= time_ago_in_words(bid.created_at) %> ago</p>
      <% if can?(:destroy, bid) %>
        <%= link_to(
          'Delete',
          bid_path(bid),
          data: {confirm: 'Are you sure?'},
          method: :delete
        ) %>
      <% end %>

  <% end %>